apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: a3fb54d7fd200a823d1024f508f9bf2b868369f23a2090e4eb5e4656814b6ffb
    cni.projectcalico.org/podIP: 10.244.120.72/32
    cni.projectcalico.org/podIPs: 10.244.120.72/32
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"app":"nginx","tier":"frontend"},"name":"nginx-pod","namespace":"frontend"},"spec":{"containers":[{"image":"nginx:latest","name":"nginx","ports":[{"containerPort":80}]}]}}
  creationTimestamp: "2026-04-10T13:47:00Z"
  generation: 1
  labels:
    app: nginx
    tier: frontend
  name: nginx-pod
  namespace: frontend
  resourceVersion: "6178"
  uid: 937176f8-d37c-4ea4-ae28-8588dd4256e5
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-zsqgq
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-zsqgq
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-04-21T18:48:47Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-04-10T13:47:00Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-04-21T18:48:47Z"
    observedGeneration: 1
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-04-21T18:48:47Z"
    observedGeneration: 1
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-04-10T13:47:00Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://0dc443753b4fac15f390c421906be730f907f1ed5382f1df1a2b28dadf5cc928
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:7f0adca1fc6c29c8dc49a2e90037a10ba20dc266baaed0988e9fb4d0d8b85ba0
    lastState:
      terminated:
        containerID: docker://47db9268a85a607c488ab31e0e78e92e7bec9b44dfac06377c8c93e4b6548e2e
        exitCode: 0
        finishedAt: "2026-04-10T14:44:55Z"
        reason: Completed
        startedAt: "2026-04-10T13:51:35Z"
    name: nginx
    ready: true
    resources: {}
    restartCount: 1
    started: true
    state:
      running:
        startedAt: "2026-04-21T18:48:44Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-zsqgq
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.49.2
  hostIPs:
  - ip: 192.168.49.2
  observedGeneration: 1
  phase: Running
  podIP: 10.244.120.72
  podIPs:
  - ip: 10.244.120.72
  qosClass: BestEffort
  startTime: "2026-04-10T13:47:00Z"
